/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── JalPramaan Material Palette ──
        "primary":                    "#00685f",
        "on-primary":                 "#ffffff",
        "primary-container":          "#008378",
        "on-primary-container":       "#f4fffc",
        "primary-fixed":              "#89f5e7",
        "primary-fixed-dim":          "#6bd8cb",
        "on-primary-fixed":           "#00201d",
        "on-primary-fixed-variant":   "#005049",
        "secondary":                  "#006398",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#5bb8fe",
        "secondary-fixed":            "#cce5ff",
        "secondary-fixed-dim":        "#93ccff",
        "on-secondary-container":     "#00476e",
        "on-secondary-fixed":         "#001d31",
        "on-secondary-fixed-variant": "#004b73",
        "tertiary":                   "#006947",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#00855b",
        "on-tertiary-container":      "#f5fff6",
        "tertiary-fixed":             "#6ffbbe",
        "tertiary-fixed-dim":         "#4edea3",
        "on-tertiary-fixed":          "#002113",
        "on-tertiary-fixed-variant":  "#005236",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "surface":                    "#faf8ff",
        "surface-dim":                "#d2d9f4",
        "surface-bright":             "#faf8ff",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f3ff",
        "surface-container":          "#eaedff",
        "surface-container-high":     "#e2e7ff",
        "surface-container-highest":  "#dae2fd",
        "surface-variant":            "#dae2fd",
        "on-surface":                 "#131b2e",
        "on-surface-variant":         "#3d4947",
        "outline":                    "#6d7a77",
        "outline-variant":            "#bcc9c6",
        "inverse-surface":            "#283044",
        "inverse-on-surface":         "#eef0ff",
        "inverse-primary":            "#6bd8cb",
        "surface-tint":               "#006a61",
        "background":                 "#faf8ff",
        "on-background":              "#131b2e",
        // ── New Pastel Tokens ──
        "aqua":   { 50: "#e0f9f7", 100: "#b3f0eb", 200: "#7de6de", 300: "#45dbd1", 400: "#17d0c5", 500: "#00bfb0" },
        "sage":   { 50: "#f0faf2", 100: "#d4f0da", 200: "#a9e1b4", 300: "#79cf8c", 400: "#51bf6c", 500: "#34a853" },
        "blush":  { 50: "#fef0f3", 100: "#fdd8df", 200: "#fbb0bf", 300: "#f8859c", 400: "#f55f7e", 500: "#f23d61" },
        "mist":   { 50: "#f0f4ff", 100: "#dce6ff", 200: "#b9ceff", 300: "#92b4ff", 400: "#6d9aff", 500: "#4c82f5" },
        "amber":  { 50: "#fff8e1", 100: "#ffecb3", 200: "#ffe082", 300: "#ffd54f", 400: "#ffca28", 500: "#ffc107" },
        // ── Glass & Cyber ──
        "glass":  "rgba(255,255,255,0.65)",
        "cyber-green": "#00ff88",
        "cyber-dark":  "#0a0f1e",
      },
      fontFamily: {
        sans:         ["Inter", "sans-serif"],
        "space":      ["Space Grotesk", "sans-serif"],
        "body-lg":    ["Inter", "sans-serif"],
        "body-sm":    ["Inter", "sans-serif"],
        "body-md":    ["Inter", "sans-serif"],
        "label-md":   ["Inter", "sans-serif"],
        "headline-md":["Inter", "sans-serif"],
        "headline-lg":["Inter", "sans-serif"],
        "display-sm": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "mono":       ["Courier New", "Courier", "monospace"],
      },
      borderRadius: {
        "bento": "24px",
        "card":  "18px",
      },
      animation: {
        'spin-slow':    'spin 3s linear infinite',
        'spin-fast':    'spin 0.6s linear infinite',
        'ping-slow':    'ping 2s cubic-bezier(0,0,0.2,1) infinite',
        'bounce-sm':    'bounceSm 1.5s ease-in-out infinite',
        'shimmer':      'shimmer 2.5s linear infinite',
        'fade-in':      'fadeIn 0.5s ease forwards',
      },
      keyframes: {
        bounceSm: {
          '0%,100%': { transform: 'translateY(0)' },
          '50%':     { transform: 'translateY(-5px)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          from: { opacity: 0 },
          to:   { opacity: 1 },
        },
      },
      backdropBlur: {
        xs: '4px',
        xl: '20px',
        '2xl': '32px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0,0,0,0.08), 0 2px 8px rgba(0,0,0,0.04)',
        'clay': '0 4px 16px rgba(0,0,0,0.12), 0 1px 4px rgba(0,0,0,0.08)',
        'glow-teal': '0 0 20px rgba(0,104,95,0.35)',
        'glow-red':  '0 0 20px rgba(239,68,68,0.35)',
        'glow-blue': '0 0 20px rgba(59,130,246,0.35)',
      },
    },
  },
  plugins: [],
}
